---
driver:
  name: vagrant

provisioner:
  name: chef_zero

verifier:
  name: inspec

platforms:
  - name: centos-7.1
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[example::default]
    attributes:
