name 'example'
maintainer 'Glauco Oliveira'
maintainer_email 'gl4uc0@gmail.com'
description 'An example of how to test cookbooks using InSpec'
issues_url 'https://github.com/glauco/provisioning-tests-talk/issues'
source_url 'https://github.com/glauco/provisioning-tests-talk'
version '0.0.1'
depends 'apt'
depends 'yum'
